### ISSUE TITLE
Add tut-based documentation

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#453]
See: https://github.com/tpolecat/tut/blob/master/README.md

This allows us to put scala code in markdown and then typecheck it so it does not get out of sync. Travis can build the docs and the build is red if something changes.

**Comment by sid-kap** [comment]
Is there a way to make Travis work with Github wiki?

**Comment by johnynek** [comment]
well, maybe not with the wiki, but possibly with README.md. We could use tut to generate it, then a script to move it into place, or something like that.

**Comment by sid-kap** [comment]
Would it be a good idea to get rid of the Wiki and use Github Pages (with Jekyll, or a similar static site generator) instead?
I see a few potential benefits:
- We could use Travis CI to integrate Tut
- Github Pages would allow us to have pull requests, branches, etc. for the docs
- The static site generator would auto-generate the Table of Contents/sidebar for us. (This isn't such a big deal for Algebird, since Algebird's wiki has only 5 pages, but it would make a big difference for the Scalding docs. In the Scalding wiki, both the homepage and the sidebar need to be updated every time someone adds a new page to the wiki.)

**Comment by sritchie** [comment]
I'm going to take this task on, both the original `tut` suggestion and @sid-kap 's suggestion to replace the wiki with a microsite.

**Comment by sritchie** [comment]
handled by #556
