### ISSUE TITLE
CMSItem disregards count in ++

### ISSUE THREAD

**Issue by johnynek** [twitter/algebird#459]
https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala#L449

note that if you do `CMSZero + ("a", 100) + ("a", 1)`, I think you'll get the same as `CMSZero + ("a", 1) + ("a", 1)`

**Comment by reconditesea** [comment]
@johnynek What's the definition of a CMSItem? 
If it's one single key with one element, I think there is no bug. If it's one single key with multiple counts, then I think both the frequency and innerProduct also need to be updated.

**Comment by jnievelt** [comment]
That's not the definition.  It's a bit weird because `CMSMonoid#create` doesn't take a count parameter (it's implicitly 1), but `CMSZero#+` does.  Basically there's not a way to hit this without involving `CMSZero`.

While we're at it, let's fix `frequency`:

https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala#L454

**Comment by reconditesea** [comment]
Yeah, both frequency and innerProduct are updated.

**Comment by reconditesea** [comment]
I believe this is closed by #464 .
